#!/bin/bash

####################################################################################################
# Name:         openSUSE Baldur (MicroOS with XFCE) - User Configurator                            #
# Description:  This file will configure the user settings on openSUSE Baldur.                     #
# Author:       Steve Zabka                                                                        #
# Author URI:   https://cryinkfly.com                                                              #
# License:      MIT                                                                                #
# Copyright (c) 2023                                                                               #
# Time/Date:    11:45/08.12.2023                                                                   #
# Version:      1.0.2                                                                              #
####################################################################################################

##############################################################################################################################################################################

# Checks if I am a root user?
function CHECK_ROOT_SHELL {
    if [ $(id -u) -eq 0 ]; then
        GET_USERDATA
    else
        # Exit/Crash ...
        zenity --error --title="Ein Fehler ist aufgetreten" --text="Dieses Anwendung darf nur als Root-Benutzer ausgeführt werden!"
	      exit 2
    fi
}

##############################################################################################################################################################################

# Show a GUI for creating the new user ...
function GET_USERDATA {
    userdata=`zenity --forms \
        --title="Benutzerkonto anlegen" \
        --text="<span font='9'>Sie müssen einen <span color='#2C423F'>Benutzername</span> für die reguläre\n(nicht-administrative) Nutzung Ihres Systems anlegen.\nUm einen <span color='#2C423F'>System-Benutzernamen</span> anzulegen, geben\nSie unten die erforderlichen Informationen ein.</span>" \
        --add-entry="Vollständiger Name:" \
        --add-entry="Benutzername:" \
        --add-password="Passwort:" \
        --add-password="Passwort bestätigen:" \
        --separator="," \
        --ok-label="Benutzer hinzufügen" \
        --cancel-label="Überspringen"`

    accepted=$?
    if ((accepted != 0)); then
        zenity --info --title="Wichtige Information" --text="Die Einrichtung eines neuen Benutzerkontos wurde übersprungen! Sie können jederzeit über die XFCE-Settings einen neuen Benutzer anlegen."
        exit 1
    fi

    name=$(awk -F, '{print $1}' <<<$userdata)
    username=$(awk -F, '{print $2}' <<<$userdata)
    password0=$(awk -F, '{print $3}' <<<$userdata)
    password1=$(awk -F, '{print $4}' <<<$userdata)
    
    CHECK_USERNAME
}

##############################################################################################################################################################################

# Checks if the new user does not already exist on this system!
function CHECK_USERNAME {
    egrep "^$username" /etc/passwd >/dev/null
    if [ $? -eq 0 ]; then
		zenity --warning --title="Ein Fehler ist aufgetreten" --text="Der eingegebene Benutzername ist auf diesem System bereits vorhanden!\nBitte wähle einen anderen Benutzername."
		GET_USERDATA
	else
		CHECK_PASSWORD
	fi
}

##############################################################################################################################################################################

# Check if passwords match and if not ask again!
function check_password {
    if [ $password0 == $password1 ]; then
        pass=$(perl -e 'print crypt($ARGV[0], "password")' $password0)
        CREATE_USER
    else
        zenity --warning --title="Ein Fehler ist aufgetreten" --text="Die eingegebenen Passwörter stimmen nicht überein!"
        GET_USERDATA
  fi
}

##############################################################################################################################################################################

# Creates a new user account with the home directory ...
function CREATE_USER {
    useradd -m -p "$pass" "$username"
    zenity --info --title="Benutzerkonto anlegen" --text="Das Benutzerkonto wurde erfolgreich angelegt und Sie werden nun abgemeldet, um sich mit dem neuen Benutzerkonto anmelden zu können!"
}

##############################################################################################################################################################################

CHECK_ROOT_SHELL
