#!/bin/bash

####################################################################################################
# Name:         openSUSE Baldur (MicroOS with XFCE) - MicroOS Desktop Firstboot                    #
# Description:  This file performs an xfce initial setup!                                          #
# Author:       Steve Zabka                                                                        #
# Author URI:   https://cryinkfly.com                                                              #
# License:      MIT                                                                                #
# Copyright (c) 2023                                                                               #
# Time/Date:    xx:xx/xx.xx.202x                                                                   #
# Version:      1.1.x                                                                              #
####################################################################################################

##############################################################################################################################################################################
# CONFIGURATION OF THE COLOR SCHEME:                                                                                                                                         #
##############################################################################################################################################################################

function LOAD_COLOR_SHEME {
    RED=$'\033[0;31m'
    YELLOW=$'\033[0;33m'
    GREEN=$'\033[0;32m'
    DARK_GREEN_COPPER="#2C423F"
    NOCOLOR=$'\033[0m'
}

############################################################################################################################################################################### 
# THE TEXTS FOR THE DIALOGUES ARE RETRIEVED HERE:                                                                                                                               #
###############################################################################################################################################################################

function GET_LOCALE_DATA {
case "$locale_data" in
  "af_ZA.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/af-ZA/locale.txt`
    ;;
  "sq_AL.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/sq-AL/locale.txt`
    ;;
  "ar_SA.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ar-SA/locale.txt`
    ;;
  "eu_ES.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/eu-ES/locale.txt`
    ;;
  "be_BY.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/be-BY/locale.txt`
    ;;
  "bs_BA.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/bs-BA/locale.txt`
    ;;
  "bg_BG.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/bg-BG/locale.txt`
    ;;
  "ca_ES.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ca-ES/locale.txt`
    ;;
  "hr_HR.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/hr-HR/locale.txt`
    ;;
  "zh_CN.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/zh-CN/locale.txt`
    ;;
  "zh_TW.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/zh-TW/locale.txt`
    ;;
  "cs_CZ.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/cs-CZ/locale.txt`
    ;;
  "da_DK.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/da-DK/locale.txt`
    ;;
  "nl_NL.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/nl-NL/locale.txt`
    ;;
  "et_EE.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/et-EE/locale.txt`
    ;;
  "fi_FI.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/fi-FI/locale.txt`
    ;;
  "fr*")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/fr-FR/locale.txt`
    ;;
  "ga_IE.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ga-IE/locale.txt`
    ;;
  "gl_ES.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/gl-ES/locale.txt`
    ;;
  "ka_GE.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ka-GE/locale.txt`
    ;;
  "de_DE.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/de-DE/ocale.txt`
    ;;
  "el_GR.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/el-GR/locale.txt`
    ;;
  "he_IL.utf8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/he-IL/locale.txt`
    ;;
  "hu_HU.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/hu-HU/locale.txt`
    ;;
  "is_IS.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/is-IS/locale.txt`
    ;;
  "id_ID.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/id-ID/locale.txt`
    ;;
  "it_IT.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/it-IT/locale.txt`
    ;;
  "ja_JP.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ja-JP/locale.txt`
    ;;
  "ko_KR.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ko-KR/locale.txt`
    ;;
  "lt_LT.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/lt-LT/locale.txt`
    ;;
  "ms_MY.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ms-MY/locale.txt`
    ;;
  "mi_NZ.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/mi-NZ/locale.txt`
    ;;
  "*NO.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/no-NO/locale.txt`
    ;;
  "pl_PL.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/pl-PL/locale.txt`
    ;;
  "pt_*UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/pt-PT/locale.txt`
    ;;
  "ro_RO.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ro-RO/locale.txt`
    ;;
  "ru_RU.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/ru-RU/locale.txt`
    ;;
  "sk_SK.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/sk-SK/locale.txt`
    ;;
  "sl_SI.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/sl-SI/locale.txt`
    ;;
  "so_SO.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/so-SO/locale.txt`
    ;;
  "es_ES.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/es-ES/locale.txt`
    ;;
  "sv_SE.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/sv-SE/locale.txt`
    ;;
  "tl_PH.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/tl-PH/locale.txt`
    ;;
  "th_TH.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/th-TH/locale.txt`
    ;;
  "tr_TR.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/tr-TR/locale.txt`
    ;;
  "uk_UA.UTF-8")
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/uk-UA/locale.txt`
    ;;
  *)
    read_locale_file=`cat /usr/bin/xfce-initial-setup/resources/locale/en-US/locale.txt`
    ;;
esac
}

###############################################################################################################################################################################
# THIS CHECKS WHETHER THE SCRIPT IS EXECUTED IN THE ROOT SHELL:                                                                                                               #
###############################################################################################################################################################################

# Checks if I am a root user and if I run the Xfce-Initial-Setup in the first time?
function CHECK_ROOT_SHELL {
    if [ $(id -u) -eq 0 ]; then
        firstboot_autostart_file="/root/.config/autostart/mod-firstboot.desktop"
        if [ -f $firstboot_autostart_file ]; then
            # Firstboot-Autostart-File exists.
            XFCE-INITIAL-SETUP-START
        else
            # Firstboot-Autostart-File does not exist.
            CHECK_WHICH_TOOL_TO_USE
        fi
    else
        CHECK_WHICH_TOOL_TO_USE
    fi
}

###############################################################################################################################################################################
# THIS CHECKS WHICH SPECIAL FUNCTION SHOULD BE CALLED:                                                                                                                        #
###############################################################################################################################################################################

function CHECK_WHICH_TOOL_TO_USE {
case "$tool_data" in
  "locale_settings_tool")
    source /usr/bin/mod-locale-setup
    ;;
  "user_settings_tool")
    source /usr/bin/mod-user-settings
    ;;
  *)
    # Nothing to do ...
    ;;
esac
}

###############################################################################################################################################################################
# THE FIRSTBOOT PROGRAM IS STARTED HERE:                                                                                                                                      #
###############################################################################################################################################################################

LOAD_COLOR_SHEME
GET_LOCALE_DATA
CHECK_ROOT_SHELL
# ...










###############################################################################################################################################################################


# Delete the desktop file for the Firstboot-Setup (/root/...)
rm -f /root/.config/autostart/mod-firstboot.desktop

# Deactivate the Automatic-Login function:
sed -i 's/DISPLAYMANAGER_AUTOLOGIN="root"/DISPLAYMANAGER_AUTOLOGIN=""/' /etc/sysconfig/displaymanager

CHECK_LOCALE_FOR_COMPLETED_SETUP_INFO
COMPLETED_SETUP_INFO

# Logout the system-user ...
xfce4-session-logout --logout
