#!/bin/bash

####################################################################################################
# Name:         openSUSE Baldur (MicroOS with XFCE) - MicroOS Desktop Firstboot                    #
# Description:  This file performs an xfce initial setup!                                          #
# Author:       Steve Zabka                                                                        #
# Author URI:   https://cryinkfly.com                                                              #
# License:      MIT                                                                                #
# Copyright (c) 2023                                                                               #
# Time/Date:    xx:xx/xx.xx.xxxx                                                                   #
# Version:      1.1.x                                                                              #
####################################################################################################

function CHECK_LOCALE__FOR_COMPLETED_SETUP_INFO {
case "$locale_data" in
  "af_ZA.UTF-8")
    info_title="Inligting"
    info_text=""
    locale_info
    ;;
  "sq_AL.UTF-8")
    info_title="Informacion"
    info_text=""
    locale_info
    ;;
  "ar_SA.UTF-8")
    info_title="معلومات"
    info_text=""
    locale_info
    ;;
  "eu_ES.UTF-8")
    info_title="Informazioa"
    info_text=""
    locale_info
    ;;
  "be_BY.UTF-8")
    info_title="Інфармацыя"
    info_text=""
    locale_info
    ;;
  "bs_BA.UTF-8")
    info_title="Informacije"
    info_text=""
    locale_info
    ;;
  "bg_BG.UTF-8")
    info_title="Информация"
    info_text=""
    locale_info
    ;;
  "ca_ES.UTF-8")
    info_title="Informació"
    info_text=""
    locale_info
    ;;
  "hr_HR.UTF-8")
    info_title="Informacije"
    info_text=""
    locale_info
    ;;
  "zh_CN.UTF-8")
    info_title="信息"
    info_text=""
    locale_info
    ;;
  "zh_TW.UTF-8")
    info_title="資訊"
    info_text=""
    locale_info
    ;;
  "cs_CZ.UTF-8")
    info_title="Informace"
    info_text=""
    locale_info
    ;;
  "da_DK.UTF-8")
    info_title="Information"
    info_text=""
    locale_info
    ;;
  "nl_NL.UTF-8")
    info_title="Informatie"
    info_text=""
    locale_info
    ;;
  "et_EE.UTF-8")
    info_title="Teave"
    info_text=""
    locale_info
    ;;
  "fi_FI.UTF-8")
    info_title="Tiedot"
    info_text=""
    locale_info
    ;;
  "fr*")
    info_title="Informations"
    info_text=""
    locale_info
    ;;
  "ga_IE.UTF-8")
    info_title="Fiosrachadh"
    info_text=""
    locale_info
    ;;
  "gl_ES.UTF-8")
    info_title="Información"
    info_text=""
    locale_info
    ;;
  "ka_GE.UTF-8")
    info_title="ინფორმაცია"
    info_text=""
    locale_info
    ;;
  "de_DE.UTF-8")
    info_title="Informationen"
    info_text=""
    locale_info
    ;;
  "el_GR.UTF-8")
    info_title="Πληροφορίες"
    info_text=""
    locale_info
    ;;
  "he_IL.utf8")
    info_title="מידע"
    info_text=""
    locale_info
    ;;
  "hu_HU.UTF-8")
    info_title="Információ"
    info_text=""
    locale_info
    ;;
  "is_IS.UTF-8")
    info_title="Upplýsingar"
    info_text=""
    locale_info
    ;;
  "id_ID.UTF-8")
    info_title="Informasi"
    info_text=""
    locale_info
    ;;
  "it_IT.UTF-8")
    info_title="Informazioni"
    info_text=""
    locale_info
    ;;
  "ja_JP.UTF-8")
    info_title="お知らせ"
    info_text=""
    locale_info
    ;;
  "ko_KR.UTF-8")
    info_title="정보"
    info_text=""
    locale_info
    ;;
  "lt_LT.UTF-8")
    info_title="Informacija"
    info_text=""
    locale_info
    ;;
  "ms_MY.UTF-8")
    info_title="Maklumat"
    info_text=""
    locale_info
    ;;
  "mi_NZ.UTF-8")
    info_title="Mohiohio"
    info_text=""
    locale_info
    ;;
  "*NO.UTF-8")
    info_title="Informasjon"
    info_text=""
    locale_info
    ;;
  "pl_PL.UTF-8")
    info_title="Informacja"
    info_text=""
    locale_info
    ;;
  "pt_*UTF-8")
    info_title="Informações"
    info_text=""
    locale_info
    ;;
  "ro_RO.UTF-8")
    info_title="Informații"
    info_text=""
    locale_info
    ;;
  "ru_RU.UTF-8")
    info_title="Информация"
    info_text=""
    locale_info
    ;;
  "mi_NZ.UTF-8")
    info_title="Fa'amatalaga"
    info_text=""
    locale_info
    ;;
  "sk_SK.UTF-8")
    info_title="Informácie"
    info_text=""
    locale_info
    ;;
  "sl_SI.UTF-8")
   info_title="Informacije"
    info_text=""
    locale_info
    ;;
  "so_SO.UTF-8")
    info_title="Macluumaad"
    info_text=""
    locale_info
    ;;
  "es_ES.UTF-8")
    info_title="Información"
    info_text=""
    locale_info
    ;;
  "sv_SE.UTF-8")
    info_title="Information"
    info_text=""
    locale_info
    ;;
  "tl_PH.UTF-8")
    info_title="Impormasyon"
    info_text=""
    locale_info
    ;;
  "th_TH.UTF-8")
    info_title="ข้อมูล"
    info_text=""
    locale_info
    ;;
  "tr_TR.UTF-8")
    info_title="Bilgi"
    info_text=""
    locale_info
    ;;
  "uk_UA.UTF-8")
    info_title="Інформація"
    info_text="Налаштування першого завантаження успішно завершено! Зміни набудуть чинності автоматично після повторного входу!"
    locale_info
    ;;
  *)
    info_title="Information"
    info_text="Firstboot configuration was completed successfully! The changes will take effect automatically after you log in again!"
    locale_info
    ;;
esac
}

function COMPLETED_SETUP_INFO {
    zenity --info \
           --title="$info_title" \
           --text="$info_text"
}

#####################################################################################################################################################################################################################
# THE FIRSTBOOT PROGRAM IS STARTED HERE:                                                                                                                                                                            #
#####################################################################################################################################################################################################################

source /usr/bin/mod-locale-setup
source /usr/bin/mod-useradd-setup
source /usr/bin/mod-flatpak-setup

# Delete the desktop file for the Firstboot-Setup (/root/...)
rm -f /root/.config/autostart/mod-firstboot.desktop

# Deactivate the Automatic-Login function:
sed -i 's/DISPLAYMANAGER_AUTOLOGIN="root"/DISPLAYMANAGER_AUTOLOGIN=""/' /etc/sysconfig/displaymanager

CHECK_LOCALE__FOR_COMPLETED_SETUP_INFO
COMPLETED_SETUP_INFO

# Logout the system-user ...
xfce4-session-logout --logout
