#!/usr/bin/bash	

####################################################################################################
# Name:         openSUSE Baldur (MicroOS with XFCE) - XFCE-Initial-Setup                           #
# Description:  This file calls the graphical XFCE-Initial-Setup!                                  #
# Author:       Steve Zabka                                                                        #
# Author URI:   https://cryinkfly.com                                                              #
# License:      MIT                                                                                #
# Copyright (c) 2023                                                                               #
# Time/Date:    xx:xx/xx.xx.xxxx                                                                   #
# Version:      1.0.0                                                                              #
####################################################################################################

function LOAD_LOCALE_SETUP {
    source ~/usr/bin/xfc4-locale-settings
}

function CREATE_NEW_USER {
    python3 ~/usr/bin/xfce-initial_add-user-setup
}

###############################################################################################################################################################################
# THE FIRSTBOOT PROGRAM IS STARTED HERE:                                                                                                                                      #
###############################################################################################################################################################################

LOAD_LOCALE_SETUP
CREATE_NEW_USER




Der kommende Inhalt muss in die "xfce4-initial-add-user-setup" eingebaut werden:

# Delete the desktop file for the Firstboot-Setup (/root/...)
rm -f /root/.config/autostart/xfce-initial-setup.desktop

# Deactivate the Automatic-Login function:
sed -i 's/DISPLAYMANAGER_AUTOLOGIN="root"/DISPLAYMANAGER_AUTOLOGIN=""/' /etc/sysconfig/displaymanager

# Logout the system-user ...
xfce4-session-logout --logout
