#!/bin/bash

####################################################################################################
# Name:         openSUSE Baldur (MicroOS with XFCE) - Locale Configurator                          #
# Description:  This file will configure the locale settings for the XFCE desktop enviroment.      #
# Author:       Steve Zabka                                                                        #
# Author URI:   https://cryinkfly.com                                                              #
# License:      MIT                                                                                #
# Copyright (c) 2023                                                                               #
# Time/Date:    23:25/08.12.2023                                                                   #
# Version:      1.0.2                                                                              #
####################################################################################################

function locale_menu {
    locale_data=$(cat /usr/etc/locale-list.txt | tr ',' '\n' | zenity --list \
        --title="Welcome" \
        --text="Please select your language:"\
        --column="" --column="" --hide-column=2 --print-column=2)

    clear
    locale_config_start
}

function locale_config_start {
# Check if the variable is empty
    if [ -z "$locale_data" ]; then
        locale_config_reset
    else
        locale_config
    fi
}

function locale_config {
echo "export LANGUAGE=$locale_data
export LANG=$locale_data
export LC_ALL=$locale_data" > $HOME/.i18n

locale_info
}

function locale_config_reset {
echo "export LANGUAGE=en_US.UTF8
export LANG=en_US.UTF8
export LC_ALL=en_US.UTF8" > $HOME/.i18n
}

function check_locale {
case "$locale_data" in
  "af_ZA.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "sq_AL.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ar_SA.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "eu_ES.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "be_BY.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "bs_BA.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "bg_BG.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ca_ES.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "hr_HR.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "zh_CN.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "zh_TW.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "cs_CZ.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "da_DK.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "nl_NL.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "et_EE.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "fi_FI.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "fr_FR.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "fr_CH.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "fr_BE.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "fr_CA.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ga_IE.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "gl_ES.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ka_GE.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "de_DE.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "el_GR.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "he_IL.utf8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "hu_HU.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "is_IS.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "id_ID.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "it_IT.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ja_JP.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ko_KR.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "lt_LT.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ms_MY.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "mi_NZ.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "no_NO.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "nn_NO.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "pl_PL.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "pt_PT.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "pt_BR.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ro_RO.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "ru_RU.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "mi_NZ.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "sk_SK.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "sl_SI.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "so_SO.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "es_ES.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "sv_SE.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "tl_PH.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "th_TH.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "mi_NZ.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "tr_TR.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;

  "uk_UA.UTF-8")
    info_title=""
    info_text=""
    warning_title=""
    warning_text=""
    locale_info
    ;;
  
  *)
    info_title="Information"
    info_text="The language settings have been successfully applied. The changes will take effect automatically after you log in again!"
    warning_title="Warning"
    warning_text="However, the keyboard language settings must be changed manually via the XFCE settings!"
    locale_info
    ;;
esac
}

function locale_info {
    zenity --info \
           --text="The language settings have been successfully applied. The changes take effect automatically the next time you log in!"
    zenity --warning \
           --text="However, the keyboard language settings must be changed manually via the XFCE settings!"
}

locale_menu
